/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package filrougel2.Views;

/**
 *
 * @author Antoine Demarly
 */
public class Param extends javax.swing.JFrame {

    /**
     * Creates new form Param
     */
    public Param() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlgue = new javax.swing.JLabel();
        jLabelAlgueNb = new javax.swing.JLabel();
        jLabelAlgueDeplacement = new javax.swing.JLabel();
        jLabelAlgueDensiteMax = new javax.swing.JLabel();
        jLabelAlgueTempsSurvie = new javax.swing.JLabel();
        jLabelAlgueTxRepro = new javax.swing.JLabel();
        jTextFieldTailleL = new javax.swing.JTextField();
        jTextFieldAlgueDeplacement = new javax.swing.JTextField();
        jTextFieldAlgueTempsSurvie = new javax.swing.JTextField();
        jTextFieldAlgueDensiteMax = new javax.swing.JTextField();
        jTextFieldAlgueTxRepro = new javax.swing.JTextField();
        jLabelAlgueNbUnite = new javax.swing.JLabel();
        jLabelAlgueDeplacementUnite = new javax.swing.JLabel();
        jLabelAlgueTempsSurvieUnite = new javax.swing.JLabel();
        jLabelAlgueTxReproUnite = new javax.swing.JLabel();
        jLabelAlgueDensiteMaxUnite = new javax.swing.JLabel();
        jTextFieldPoissonTempsSurvie = new javax.swing.JTextField();
        jLabelPoissonNbUnite = new javax.swing.JLabel();
        jTextFieldPoissonNb = new javax.swing.JTextField();
        jLabelPoissonDeplacementUnite = new javax.swing.JLabel();
        jTextFieldPoissonDeplacement = new javax.swing.JTextField();
        jLabelPoissonTempsSurvieUnite = new javax.swing.JLabel();
        jLabelPoissonTempsSurvie = new javax.swing.JLabel();
        jLabelPoissonTxReproUnite = new javax.swing.JLabel();
        jLabelPoissonTxRepro = new javax.swing.JLabel();
        jLabelPoissonDensiteMaxUnite = new javax.swing.JLabel();
        jLabelPoissonDeplacement = new javax.swing.JLabel();
        jLabelPoissonDensiteMax = new javax.swing.JLabel();
        jLabelPoisson = new javax.swing.JLabel();
        jLabelPoissonNb = new javax.swing.JLabel();
        jTextFieldPoissonTxRepro = new javax.swing.JTextField();
        jTextFieldPoissonDensiteMax = new javax.swing.JTextField();
        jLabelRequinTxRepro = new javax.swing.JLabel();
        jLabelRequinDensiteMaxUnite = new javax.swing.JLabel();
        jLabelRequinTempsSurvie = new javax.swing.JLabel();
        jLabelRequinTxReproUnite = new javax.swing.JLabel();
        jLabelRequin = new javax.swing.JLabel();
        jLabelRequinDeplacement = new javax.swing.JLabel();
        jLabelRequinDensiteMax = new javax.swing.JLabel();
        jTextFieldRequinDensiteMax = new javax.swing.JTextField();
        jTextFieldRequinTxRepro = new javax.swing.JTextField();
        jLabelRequinNb = new javax.swing.JLabel();
        jTextFieldRequinTempsSurvie = new javax.swing.JTextField();
        jLabelRequinNbUnite = new javax.swing.JLabel();
        jTextFieldRequinNb = new javax.swing.JTextField();
        jLabelRequinDeplacementUnite = new javax.swing.JLabel();
        jLabelRequinTempsSurvieUnite = new javax.swing.JLabel();
        jTextFieldRequinDeplacement = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jLabelTaille = new javax.swing.JLabel();
        jLabelTailleLargeur = new javax.swing.JLabel();
        jLabelTailleHauteur = new javax.swing.JLabel();
        jTextFieldAlgueNb = new javax.swing.JTextField();
        jTextFieldTailleH = new javax.swing.JTextField();
        jLabelTailleLUnite = new javax.swing.JLabel();
        jLabelTailleHUnite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAlgue.setText("Algue");

        jLabelAlgueNb.setText("Nombre :");

        jLabelAlgueDeplacement.setText("Se deplacer :");

        jLabelAlgueDensiteMax.setText("Densité max :");

        jLabelAlgueTempsSurvie.setText("Temps de survie :");

        jLabelAlgueTxRepro.setText("Taux de reproduction :");

        jTextFieldTailleL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTailleL.setText("120");

        jTextFieldAlgueDeplacement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAlgueDeplacement.setText("1");

        jTextFieldAlgueTempsSurvie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAlgueTempsSurvie.setText("200");

        jTextFieldAlgueDensiteMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAlgueDensiteMax.setText("80");

        jTextFieldAlgueTxRepro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldAlgueTxRepro.setText("10");

        jLabelAlgueNbUnite.setText("Algue(s)");

        jLabelAlgueDeplacementUnite.setText("Case(s)");

        jLabelAlgueTempsSurvieUnite.setText("Tour(s)");

        jLabelAlgueTxReproUnite.setText("%");

        jLabelAlgueDensiteMaxUnite.setText("%");

        jTextFieldPoissonTempsSurvie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPoissonTempsSurvie.setText("10");

        jLabelPoissonNbUnite.setText("Poisson(s)");

        jTextFieldPoissonNb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelPoissonDeplacementUnite.setText("Case(s)");

        jTextFieldPoissonDeplacement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPoissonDeplacement.setText("2");

        jLabelPoissonTempsSurvieUnite.setText("Tour(s)");

        jLabelPoissonTempsSurvie.setText("Temps de survie :");

        jLabelPoissonTxReproUnite.setText("%");

        jLabelPoissonTxRepro.setText("Taux de reproduction :");

        jLabelPoissonDensiteMaxUnite.setText("%");

        jLabelPoissonDeplacement.setText("Se deplacer :");

        jLabelPoissonDensiteMax.setText("Densité max :");

        jLabelPoisson.setText("Poisson");

        jLabelPoissonNb.setText("Nombre :");

        jTextFieldPoissonTxRepro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPoissonTxRepro.setText("50");

        jTextFieldPoissonDensiteMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPoissonDensiteMax.setText("15");

        jLabelRequinTxRepro.setText("Taux de reproduction :");

        jLabelRequinDensiteMaxUnite.setText("%");

        jLabelRequinTempsSurvie.setText("Temps de survie :");

        jLabelRequinTxReproUnite.setText("%");

        jLabelRequin.setText("Requin");

        jLabelRequinDeplacement.setText("Se deplacer :");

        jLabelRequinDensiteMax.setText("Densité max :");

        jTextFieldRequinDensiteMax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRequinDensiteMax.setText("5");

        jTextFieldRequinTxRepro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRequinTxRepro.setText("30");

        jLabelRequinNb.setText("Nombre :");

        jTextFieldRequinTempsSurvie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRequinTempsSurvie.setText("15");

        jLabelRequinNbUnite.setText("Requin(s)");

        jTextFieldRequinNb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabelRequinDeplacementUnite.setText("Case(s)");

        jLabelRequinTempsSurvieUnite.setText("Tour(s)");

        jTextFieldRequinDeplacement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldRequinDeplacement.setText("3");

        jButtonValider.setText("Valider");
        jButtonValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonValiderMousePressed(evt);
            }
        });

        jLabelTaille.setText("Taille de l'aquarium");

        jLabelTailleLargeur.setText("Largeur :");

        jLabelTailleHauteur.setText("Hauteur :");

        jTextFieldAlgueNb.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextFieldTailleH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldTailleH.setText("90");

        jLabelTailleLUnite.setText("Case(s)");

        jLabelTailleHUnite.setText("Case(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlgue)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelAlgueNb)
                                        .addGap(249, 249, 249))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelAlgueTxRepro)
                                                    .addComponent(jLabelAlgueDensiteMax)
                                                    .addComponent(jLabelAlgueTempsSurvie))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldAlgueTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelAlgueTempsSurvieUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldAlgueDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelAlgueDensiteMaxUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldAlgueTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelAlgueTxReproUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldAlgueDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelAlgueDeplacementUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldAlgueNb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelAlgueNbUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldTailleL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelTailleLUnite))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextFieldTailleH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabelTailleHUnite))))
                                            .addComponent(jLabelAlgueDeplacement))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPoisson)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPoissonTxRepro)
                                            .addComponent(jLabelPoissonDensiteMax)
                                            .addComponent(jLabelPoissonTempsSurvie)
                                            .addComponent(jLabelPoissonNb))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPoissonTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPoissonTempsSurvieUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPoissonDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPoissonDensiteMaxUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPoissonTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPoissonTxReproUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPoissonDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPoissonDeplacementUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldPoissonNb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPoissonNbUnite))))
                                    .addComponent(jLabelPoissonDeplacement))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonValider))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTaille)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRequin)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTailleLargeur)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRequinTxRepro)
                                            .addComponent(jLabelRequinDensiteMax)
                                            .addComponent(jLabelRequinTempsSurvie)
                                            .addComponent(jLabelRequinNb))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRequinTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelRequinTempsSurvieUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRequinDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelRequinDensiteMaxUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRequinTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelRequinTxReproUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRequinDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelRequinDeplacementUnite))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldRequinNb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelRequinNbUnite))))
                                    .addComponent(jLabelRequinDeplacement)
                                    .addComponent(jLabelTailleHauteur))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTaille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTailleLargeur)
                    .addComponent(jTextFieldTailleL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTailleLUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTailleHauteur)
                    .addComponent(jTextFieldTailleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTailleHUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelAlgue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlgueNb)
                    .addComponent(jLabelAlgueNbUnite)
                    .addComponent(jTextFieldAlgueNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlgueDeplacement)
                    .addComponent(jTextFieldAlgueDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlgueDeplacementUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlgueTempsSurvie)
                    .addComponent(jTextFieldAlgueTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlgueTempsSurvieUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlgueTxRepro)
                    .addComponent(jTextFieldAlgueTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlgueTxReproUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlgueDensiteMax)
                    .addComponent(jTextFieldAlgueDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlgueDensiteMaxUnite))
                .addGap(18, 18, 18)
                .addComponent(jLabelPoisson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoissonNb)
                    .addComponent(jTextFieldPoissonNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoissonNbUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoissonDeplacement)
                    .addComponent(jTextFieldPoissonDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoissonDeplacementUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoissonTempsSurvie)
                    .addComponent(jTextFieldPoissonTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoissonTempsSurvieUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoissonTxRepro)
                    .addComponent(jTextFieldPoissonTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoissonTxReproUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPoissonDensiteMax)
                    .addComponent(jTextFieldPoissonDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPoissonDensiteMaxUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRequin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequinNb)
                    .addComponent(jTextFieldRequinNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRequinNbUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequinDeplacement)
                    .addComponent(jTextFieldRequinDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRequinDeplacementUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequinTempsSurvie)
                    .addComponent(jTextFieldRequinTempsSurvie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRequinTempsSurvieUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequinTxRepro)
                    .addComponent(jTextFieldRequinTxRepro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRequinTxReproUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRequinDensiteMax)
                    .addComponent(jTextFieldRequinDensiteMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRequinDensiteMaxUnite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValider)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonValiderMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Param.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Param().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabelAlgue;
    private javax.swing.JLabel jLabelAlgueDensiteMax;
    private javax.swing.JLabel jLabelAlgueDensiteMaxUnite;
    private javax.swing.JLabel jLabelAlgueDeplacement;
    private javax.swing.JLabel jLabelAlgueDeplacementUnite;
    private javax.swing.JLabel jLabelAlgueNb;
    private javax.swing.JLabel jLabelAlgueNbUnite;
    private javax.swing.JLabel jLabelAlgueTempsSurvie;
    private javax.swing.JLabel jLabelAlgueTempsSurvieUnite;
    private javax.swing.JLabel jLabelAlgueTxRepro;
    private javax.swing.JLabel jLabelAlgueTxReproUnite;
    private javax.swing.JLabel jLabelPoisson;
    private javax.swing.JLabel jLabelPoissonDensiteMax;
    private javax.swing.JLabel jLabelPoissonDensiteMaxUnite;
    private javax.swing.JLabel jLabelPoissonDeplacement;
    private javax.swing.JLabel jLabelPoissonDeplacementUnite;
    private javax.swing.JLabel jLabelPoissonNb;
    private javax.swing.JLabel jLabelPoissonNbUnite;
    private javax.swing.JLabel jLabelPoissonTempsSurvie;
    private javax.swing.JLabel jLabelPoissonTempsSurvieUnite;
    private javax.swing.JLabel jLabelPoissonTxRepro;
    private javax.swing.JLabel jLabelPoissonTxReproUnite;
    private javax.swing.JLabel jLabelRequin;
    private javax.swing.JLabel jLabelRequinDensiteMax;
    private javax.swing.JLabel jLabelRequinDensiteMaxUnite;
    private javax.swing.JLabel jLabelRequinDeplacement;
    private javax.swing.JLabel jLabelRequinDeplacementUnite;
    private javax.swing.JLabel jLabelRequinNb;
    private javax.swing.JLabel jLabelRequinNbUnite;
    private javax.swing.JLabel jLabelRequinTempsSurvie;
    private javax.swing.JLabel jLabelRequinTempsSurvieUnite;
    private javax.swing.JLabel jLabelRequinTxRepro;
    private javax.swing.JLabel jLabelRequinTxReproUnite;
    private javax.swing.JLabel jLabelTaille;
    private javax.swing.JLabel jLabelTailleHUnite;
    private javax.swing.JLabel jLabelTailleHauteur;
    private javax.swing.JLabel jLabelTailleLUnite;
    private javax.swing.JLabel jLabelTailleLargeur;
    private javax.swing.JTextField jTextFieldAlgueDensiteMax;
    private javax.swing.JTextField jTextFieldAlgueDeplacement;
    private javax.swing.JTextField jTextFieldAlgueNb;
    private javax.swing.JTextField jTextFieldAlgueTempsSurvie;
    private javax.swing.JTextField jTextFieldAlgueTxRepro;
    private javax.swing.JTextField jTextFieldPoissonDensiteMax;
    private javax.swing.JTextField jTextFieldPoissonDeplacement;
    private javax.swing.JTextField jTextFieldPoissonNb;
    private javax.swing.JTextField jTextFieldPoissonTempsSurvie;
    private javax.swing.JTextField jTextFieldPoissonTxRepro;
    private javax.swing.JTextField jTextFieldRequinDensiteMax;
    private javax.swing.JTextField jTextFieldRequinDeplacement;
    private javax.swing.JTextField jTextFieldRequinNb;
    private javax.swing.JTextField jTextFieldRequinTempsSurvie;
    private javax.swing.JTextField jTextFieldRequinTxRepro;
    private javax.swing.JTextField jTextFieldTailleH;
    private javax.swing.JTextField jTextFieldTailleL;
    // End of variables declaration//GEN-END:variables
}
